apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-service
  template:
    metadata:
      labels:
        app: todo-service
    spec:
      containers:
        - name: todo-service
          image: elialombardi/todo-service:latest
---
apiVersion: v1
kind: Service
metadata:
  name: todo-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: todo-service
  ports:
    - name: todo-service
      protocol: TCP
      port: 80
      targetPort: 80
